import json
import os
from web3 import Web3
from flask import current_app

# ABI file paths (generated by Hardhat compilation)
ABI_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "..", "artifacts", "contracts")

# Minimal ABIs for each contract
VOTER_REGISTRY_ABI = [
    {"inputs": [], "stateMutability": "nonpayable", "type": "constructor"},
    {
        "inputs": [{"name": "_admin", "type": "address"}],
        "name": "addAdmin",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "_wallet", "type": "address"},
            {"name": "_identityHash", "type": "bytes32"},
            {"name": "_constituencyId", "type": "uint256"},
        ],
        "name": "registerVoter",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "_wallet", "type": "address"},
            {"name": "_reason", "type": "string"},
        ],
        "name": "deactivateVoter",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"name": "_wallet", "type": "address"}],
        "name": "reactivateVoter",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"name": "_wallet", "type": "address"}],
        "name": "isEligible",
        "outputs": [{"name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"name": "_wallet", "type": "address"}],
        "name": "getVoterConstituency",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"name": "_wallet", "type": "address"}],
        "name": "getVoterInfo",
        "outputs": [
            {"name": "registered", "type": "bool"},
            {"name": "active", "type": "bool"},
            {"name": "constituencyId", "type": "uint256"},
            {"name": "registeredAt", "type": "uint256"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "totalVoters",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "_wallet", "type": "address"},
            {"name": "_identityHash", "type": "bytes32"},
        ],
        "name": "verifyIdentity",
        "outputs": [{"name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
]

ELECTION_FACTORY_ABI = [
    {
        "inputs": [{"name": "_voterRegistry", "type": "address"}],
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {
        "inputs": [{"name": "_admin", "type": "address"}],
        "name": "addAdmin",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "_name", "type": "string"},
            {"name": "_description", "type": "string"},
            {"name": "_commitDeadline", "type": "uint256"},
            {"name": "_revealDeadline", "type": "uint256"},
            {"name": "_candidateNames", "type": "string[]"},
            {"name": "_candidateParties", "type": "string[]"},
            {"name": "_constituencyId", "type": "uint256"},
            {"name": "_electionType", "type": "uint8"},
        ],
        "name": "createElection",
        "outputs": [
            {"name": "electionId", "type": "uint256"},
            {"name": "ballotAddress", "type": "address"},
        ],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getElectionCount",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"name": "_index", "type": "uint256"}],
        "name": "getElection",
        "outputs": [
            {"name": "id", "type": "uint256"},
            {"name": "name", "type": "string"},
            {"name": "description", "type": "string"},
            {"name": "ballotAddress", "type": "address"},
            {"name": "createdAt", "type": "uint256"},
            {"name": "createdBy", "type": "address"},
            {"name": "electionType", "type": "uint8"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getAllElections",
        "outputs": [
            {
                "components": [
                    {"name": "id", "type": "uint256"},
                    {"name": "name", "type": "string"},
                    {"name": "description", "type": "string"},
                    {"name": "ballotAddress", "type": "address"},
                    {"name": "createdAt", "type": "uint256"},
                    {"name": "createdBy", "type": "address"},
                    {"name": "electionType", "type": "uint8"},
                ],
                "name": "",
                "type": "tuple[]",
            }
        ],
        "stateMutability": "view",
        "type": "function",
    },
]

BALLOT_ABI = [
    {
        "inputs": [{"name": "_commitHash", "type": "bytes32"}],
        "name": "commitVote",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "_candidateId", "type": "uint256"},
            {"name": "_secret", "type": "bytes32"},
        ],
        "name": "revealVote",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "finalize",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getElectionInfo",
        "outputs": [
            {"name": "_electionId", "type": "uint256"},
            {"name": "_name", "type": "string"},
            {"name": "_commitDeadline", "type": "uint256"},
            {"name": "_revealDeadline", "type": "uint256"},
            {"name": "_totalCommits", "type": "uint256"},
            {"name": "_totalReveals", "type": "uint256"},
            {"name": "_candidateCount", "type": "uint256"},
            {"name": "_phase", "type": "uint8"},
            {"name": "_isCancelled", "type": "bool"},
            {"name": "_isFinalized", "type": "bool"},
            {"name": "_constituencyId", "type": "uint256"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getAllCandidates",
        "outputs": [
            {
                "components": [
                    {"name": "id", "type": "uint256"},
                    {"name": "name", "type": "string"},
                    {"name": "party", "type": "string"},
                    {"name": "voteCount", "type": "uint256"},
                ],
                "name": "",
                "type": "tuple[]",
            }
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getResults",
        "outputs": [
            {
                "components": [
                    {"name": "id", "type": "uint256"},
                    {"name": "name", "type": "string"},
                    {"name": "party", "type": "string"},
                    {"name": "voteCount", "type": "uint256"},
                ],
                "name": "",
                "type": "tuple[]",
            }
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"name": "_voter", "type": "address"}],
        "name": "getVoterCommitStatus",
        "outputs": [
            {"name": "hasCommitted", "type": "bool"},
            {"name": "hasRevealed", "type": "bool"},
            {"name": "receiptHash", "type": "bytes32"},
            {"name": "commitTimestamp", "type": "uint256"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "_voter", "type": "address"},
            {"name": "_receiptHash", "type": "bytes32"},
        ],
        "name": "verifyReceipt",
        "outputs": [{"name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "currentPhase",
        "outputs": [{"name": "", "type": "uint8"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "totalCommits",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "totalReveals",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "_candidateId", "type": "uint256"},
            {"name": "_secret", "type": "bytes32"},
        ],
        "name": "computeCommitHash",
        "outputs": [{"name": "", "type": "bytes32"}],
        "stateMutability": "pure",
        "type": "function",
    },
    {
        "inputs": [{"name": "_reason", "type": "string"}],
        "name": "cancelElection",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
]

VOTE_VERIFIER_ABI = [
    {
        "inputs": [{"name": "_voterRegistry", "type": "address"}],
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {
        "inputs": [
            {"name": "_ballot", "type": "address"},
            {"name": "_voter", "type": "address"},
            {"name": "_receiptHash", "type": "bytes32"},
        ],
        "name": "verifyVoterReceipt",
        "outputs": [
            {
                "components": [
                    {"name": "isRegisteredVoter", "type": "bool"},
                    {"name": "hasCommitted", "type": "bool"},
                    {"name": "hasRevealed", "type": "bool"},
                    {"name": "receiptValid", "type": "bool"},
                    {"name": "commitTimestamp", "type": "uint256"},
                    {"name": "receiptHash", "type": "bytes32"},
                ],
                "name": "result",
                "type": "tuple",
            }
        ],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"name": "_ballot", "type": "address"}],
        "name": "verifyElectionIntegrity",
        "outputs": [
            {"name": "isIntegrous", "type": "bool"},
            {"name": "totalReveals", "type": "uint256"},
            {"name": "totalCandidateVotes", "type": "uint256"},
            {"name": "totalCommits", "type": "uint256"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "_ballot", "type": "address"},
            {"name": "_voter", "type": "address"},
        ],
        "name": "didVoterParticipate",
        "outputs": [
            {"name": "committed", "type": "bool"},
            {"name": "revealed", "type": "bool"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"name": "_ballot", "type": "address"}],
        "name": "getElectionSummary",
        "outputs": [
            {"name": "name", "type": "string"},
            {"name": "totalVoters", "type": "uint256"},
            {"name": "totalRevealed", "type": "uint256"},
            {"name": "candidateCount", "type": "uint256"},
            {"name": "finalized", "type": "bool"},
            {"name": "cancelled", "type": "bool"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
]


class Web3Service:
    """Singleton service for Web3 blockchain interactions."""

    _instance = None

    def __init__(self):
        self.w3 = None
        self.account = None
        self.voter_registry = None
        self.election_factory = None
        self.vote_verifier = None

    @classmethod
    def get_instance(cls):
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def init(self, rpc_url, private_key=None, registry_addr=None, factory_addr=None, verifier_addr=None):
        self.w3 = Web3(Web3.HTTPProvider(rpc_url))

        if not self.w3.is_connected():
            raise ConnectionError(f"Cannot connect to Ethereum node at {rpc_url}")

        if private_key:
            self.account = self.w3.eth.account.from_key(private_key)

        if registry_addr:
            self.voter_registry = self.w3.eth.contract(
                address=Web3.to_checksum_address(registry_addr),
                abi=VOTER_REGISTRY_ABI,
            )

        if factory_addr:
            self.election_factory = self.w3.eth.contract(
                address=Web3.to_checksum_address(factory_addr),
                abi=ELECTION_FACTORY_ABI,
            )

        if verifier_addr:
            self.vote_verifier = self.w3.eth.contract(
                address=Web3.to_checksum_address(verifier_addr),
                abi=VOTE_VERIFIER_ABI,
            )

    def _send_tx(self, contract_fn, *args):
        """Build, sign, and send a transaction."""
        if not self.account:
            raise RuntimeError("No private key configured for sending transactions")

        tx = contract_fn(*args).build_transaction(
            {
                "from": self.account.address,
                "nonce": self.w3.eth.get_transaction_count(self.account.address),
                "gas": 3000000,
                "gasPrice": self.w3.eth.gas_price,
            }
        )
        signed = self.account.sign_transaction(tx)
        tx_hash = self.w3.eth.send_raw_transaction(signed.raw_transaction)
        receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)
        return receipt

    # --- Voter Registry ---

    def register_voter(self, wallet, identity_hash, constituency_id):
        if not self.voter_registry:
            return None
        receipt = self._send_tx(
            self.voter_registry.functions.registerVoter,
            Web3.to_checksum_address(wallet),
            identity_hash,
            constituency_id,
        )
        return receipt.transactionHash.hex()

    def is_voter_eligible(self, wallet):
        if not self.voter_registry:
            return False
        return self.voter_registry.functions.isEligible(
            Web3.to_checksum_address(wallet)
        ).call()

    def get_voter_info(self, wallet):
        if not self.voter_registry:
            return None
        result = self.voter_registry.functions.getVoterInfo(
            Web3.to_checksum_address(wallet)
        ).call()
        return {
            "registered": result[0],
            "active": result[1],
            "constituency_id": result[2],
            "registered_at": result[3],
        }

    def get_total_voters(self):
        if not self.voter_registry:
            return 0
        return self.voter_registry.functions.totalVoters().call()

    # --- Election Factory ---

    def create_election(self, name, description, commit_deadline, reveal_deadline,
                        candidate_names, candidate_parties, constituency_id, election_type):
        if not self.election_factory:
            return None, None
        receipt = self._send_tx(
            self.election_factory.functions.createElection,
            name,
            description,
            commit_deadline,
            reveal_deadline,
            candidate_names,
            candidate_parties,
            constituency_id,
            election_type,
        )
        # Parse the ElectionCreated event to get electionId and ballotAddress
        logs = self.election_factory.events.ElectionCreated().process_receipt(receipt)
        if logs:
            event = logs[0]["args"]
            return event["electionId"], event["ballotAddress"]
        return None, receipt.transactionHash.hex()

    def get_all_elections(self):
        if not self.election_factory:
            return []
        return self.election_factory.functions.getAllElections().call()

    def get_election_count(self):
        if not self.election_factory:
            return 0
        return self.election_factory.functions.getElectionCount().call()

    # --- Ballot (per-election) ---

    def get_ballot_contract(self, ballot_address):
        return self.w3.eth.contract(
            address=Web3.to_checksum_address(ballot_address),
            abi=BALLOT_ABI,
        )

    def get_election_info(self, ballot_address):
        ballot = self.get_ballot_contract(ballot_address)
        result = ballot.functions.getElectionInfo().call()
        phase_names = ["COMMIT", "REVEAL", "TALLY"]
        return {
            "election_id": result[0],
            "name": result[1],
            "commit_deadline": result[2],
            "reveal_deadline": result[3],
            "total_commits": result[4],
            "total_reveals": result[5],
            "candidate_count": result[6],
            "phase": phase_names[result[7]] if result[7] < len(phase_names) else "UNKNOWN",
            "is_cancelled": result[8],
            "is_finalized": result[9],
            "constituency_id": result[10],
        }

    def get_ballot_candidates(self, ballot_address):
        ballot = self.get_ballot_contract(ballot_address)
        candidates = ballot.functions.getAllCandidates().call()
        return [
            {"id": c[0], "name": c[1], "party": c[2], "vote_count": c[3]}
            for c in candidates
        ]

    def get_ballot_results(self, ballot_address):
        ballot = self.get_ballot_contract(ballot_address)
        candidates = ballot.functions.getResults().call()
        return [
            {"id": c[0], "name": c[1], "party": c[2], "vote_count": c[3]}
            for c in candidates
        ]

    def get_voter_commit_status(self, ballot_address, voter_address):
        ballot = self.get_ballot_contract(ballot_address)
        result = ballot.functions.getVoterCommitStatus(
            Web3.to_checksum_address(voter_address)
        ).call()
        return {
            "has_committed": result[0],
            "has_revealed": result[1],
            "receipt_hash": result[2].hex() if isinstance(result[2], bytes) else result[2],
            "commit_timestamp": result[3],
        }

    # --- Vote Verifier ---

    def verify_election_integrity(self, ballot_address):
        if not self.vote_verifier:
            return None
        result = self.vote_verifier.functions.verifyElectionIntegrity(
            Web3.to_checksum_address(ballot_address)
        ).call()
        return {
            "is_integrous": result[0],
            "total_reveals": result[1],
            "total_candidate_votes": result[2],
            "total_commits": result[3],
        }

    def get_election_summary(self, ballot_address):
        if not self.vote_verifier:
            return None
        result = self.vote_verifier.functions.getElectionSummary(
            Web3.to_checksum_address(ballot_address)
        ).call()
        return {
            "name": result[0],
            "total_voters": result[1],
            "total_revealed": result[2],
            "candidate_count": result[3],
            "finalized": result[4],
            "cancelled": result[5],
        }

    def did_voter_participate(self, ballot_address, voter_address):
        if not self.vote_verifier:
            return None
        result = self.vote_verifier.functions.didVoterParticipate(
            Web3.to_checksum_address(ballot_address),
            Web3.to_checksum_address(voter_address),
        ).call()
        return {"committed": result[0], "revealed": result[1]}

    @staticmethod
    def hash_identity(raw_id):
        """Keccak-256 hash of a voter identity string, same as Solidity."""
        return Web3.solidity_keccak(["string"], [raw_id])
